---
# file: site.yml

- name: Create AWS infrastructure
  hosts: webserver
  roles:
    - role: update
      tags: [ 'update' ]    
    - role: users
      tags: [ 'users' ]
    - role: nginx 
      tags: [ 'webserver' ]
